LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := SimpleCalendar

LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES := SimpleCalendar.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

LOCAL_OVERRIDES_PACKAGES := Etar

include $(BUILD_PREBUILT)
