LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := SimpleSMS

LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES := SimpleSMS.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

LOCAL_OVERRIDES_PACKAGES := messaging

include $(BUILD_PREBUILT)
